### PR TITLE
Add resetPassword method to User

### LINKED ISSUE #52: Add reset password mails
Allow for players to restore their password via a temporary password

### PR DESCRIPTION
**Pull request by SeineEloquenz**
Branch for the reset email feature

Todo:

- [x] Add `User::resetPassword()` method
- [x]  Add page to website where one can request a password reset for player/organiser
- [x]  Add javascript for resetPassword page
- [x]  Add API calls to actually execute the `User::resetPassword()` method
- [x]  Test whether emails get sent correctly

closes #52

### CODE REVIEW

**Comment by bendixsonnenberg** [comment]
1. don't create hash and salt in the user class. That's the job of the management classes.
2. the api can't reset the password right now, because there is no way for the api to get a user without their password. (The api really should not talk to the database directly)

**Comment by SeineEloquenz** [comment]
Moved the encryption process to the UserManagement, is now usable from there, so API should be able to reset now

**Comment by bendixsonnenberg** [comment]
I would propose increasing the length of the passwords, as the current
>Dear CS:Select User, a request to reset your CS:Select password was submitted. Your temporary password is 'w02xErBQa'! Please change this password to an own safe one as fast as possible!
9 characters are not that save

**Comment by SeineEloquenz** [comment]
There are 2 constants in the usermanagement specifying min/max length of the created password, you might change as you see fit

**Pull request merged**
