### PR TITLE
Add ConfigurationException class

### PR DESCRIPTION
**Pull request by SeineEloquenz**
ConfigurationException is thrown when an error occurs while reading the config file. Allows us to print error messages to the user if the config is missing

- [ ] Catch exception in frontend and print error if config is missing

### CODE REVIEW

**Comment by bendixsonnenberg** [comment]
I'm only getting the exception once and after that the stacktrace is:
```
java.lang.NoClassDefFoundError: Could not initialize class com.csselect.user.management.PlayerManagement
	com.csselect.API.APIFacadePlayer.login(APIFacadePlayer.java:44)
	com.csselect.API.httpAPI.Login.login(Login.java:84)
	com.csselect.API.httpAPI.Login.post(Login.java:36)
	com.csselect.API.httpAPI.Servlet.doPost(Servlet.java:102)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
```

**Comment by bendixsonnenberg** [comment]
its because the configuaration is only created once and can therefore only throw the exception once

**Comment by SeineEloquenz** [comment]
I'll look if I can catch the noclassdeffound exception where it's thrown and re-throw it as a ConfigurationException

**Comment by bendixsonnenberg** [comment]
I could do the same in the api, but that would be rather messy

**Comment by SeineEloquenz** [comment]
I'll look into it because I could do it on a lower level so we don't accidentally catch other exceptions as well. (Assuming this is possible)

**Comment by SeineEloquenz** [comment]
I looked into it and we can't get this to work by catching the exception when we create the configuration, as this kills the instantiation of the injector as well and references to the injector get saved even though instantiation didn't work out as planned. Maybe you could save in a static boolean whether the exception was thrown and check this on login as well? I don't know of a better solution as of now

**Comment by bendixsonnenberg** [comment]
in that case the static boolean should be in the injector

**Comment by SeineEloquenz** [comment]
That's the problem, if I throw the Exception in the Injector it doesn't help, as classes like for example the playerManagement (which throws the noclassdeffound exception) save static final instances of the then malformed injector

**Comment by SeineEloquenz** [comment]
I would propose that you just save whether the exception has been thrown and check against it before doing the login. If it wasn't thrown before you might run into the catch clause and set the boolean there so in the future when java doesn't throw the exception anymore as it already registered that configurations can't be constructed, we just avoid the problem via a simple if condition. Seems like the simplest solution for me atm

**Comment by bendixsonnenberg** [comment]
yes, but that is anything but good style.
I would say that no class should keep the injector, as that seems to be the root cause now

**Comment by SeineEloquenz** [comment]
I'll refactor this and try again

**Comment by SeineEloquenz** [comment]
I refactored the injector-dependent static fields and it's now working as planned on my end

**Comment by bendixsonnenberg** [comment]
can confirm, on my end as well

**Pull request merged**
