### PR TITLE
Repeat password in settings

### LINKED ISSUE #87: [feature-request][low prio] Organiser Settings: Make password change less error-prone
2nd input field to confirm password or show password so that the user can make sure that there are no typos in it.

### PR DESCRIPTION
**Pull request by SeineEloquenz**
close #87

### CODE REVIEW

**Comment by Santaaa348** [comment]
Does not work.
- You can click on update without repeating your password.
- If you repeat your password correctly , it still shows `Does not match`.

**Comment by SeineEloquenz** [comment]
Please try to hard-reload the page to load the new scripts, does it work then?

**Comment by Santaaa348** [comment]
My bad. Second point works.
**But** you can still change password without repeating. Button is grayed out, but clickable.

**Comment by SeineEloquenz** [comment]
Should be prevented now

**Pull request merged**
