### PR TITLE
Gamecreation frontend rewrite

### LINKED ISSUE #57: Success message after creating two games does not appear again
- Create a game
- Click on the cross to make success message disappear
- Create another game on the same page (change values as you like)
- Database entry is made, but no success message

### LINKED ISSUE #63: Game Creation: user is spammed with alerts
When creating a game and clicking on create before filling all fields, the user is spammed with a number of alerts that keep the user from filling the missing fields.

### LINKED ISSUE #67: Game Creation: "Game has been created" shows even if creation failed
When creating a game and not specifying the game mode before clicking "Create", an error is alerted, but after clicking ok "Game has been created" is shown. The game isn't being created.

### LINKED ISSUE #68: Game Creation: organizer can spam "Create" button
When clicking on the "create"-button repeatedly, multiple games are created. This is bad not only under the premise of malicious users, but might also happen by accident.

Suggested fix: redirect to dashboard after successfully creating the game.

### LINKED ISSUE #82: [gui][low prio] Game Creation: "(none)" drop-down is confusing
I suppose the drop-down in the top-right corner allows to select existing patterns (showing "(none)" after first login)? Some explanation would be nice (e.g., label in front).

### LINKED ISSUE #84: [gui][feature-request][low prio] Game Creation: Improve mail invitation field
Allow entering multiple mail addresses separated by some character (e.g., comma). Another (less important) enhancement is a searchable list of players (of course with the possibility to add players).

### LINKED ISSUE #108: [code][low prio] Parsers could me moved
The two parser classes from the package `parsers` could be moved to the package `utils`. This saves one rather small package and just from the naming point of view, the more general *utils* also is fine.
An alternative (probably better from the software design perspective) would be to place them in the `game` package, as they are tightly coupled to classes from there.

### PR DESCRIPTION
**Pull request by bendixsonnenberg**
Rewrite of the gamecreation frontend.

- new method of inputing players resolves #84
- move gamemode parser to the Parser class resolves  #108 
- Datetimepicker for setting timetermination #64
- termination values are now read from the pattern #103
- no alert madness resolves #63
- no more none option resolves #82
- the frontend now uses the same format for terminations and gamemodes that the database uses, which means only one parsing method instead of two

still needs to happen:

- [x] featureSet loading from pattern
- [x]  prevent spamming of create button resolves #68
- [x] response that tells the user is the game has been created successfully resolves #67, resolves #57 
- [] termination only by organiser #51 not happening
- [x] translate localisation, i'm just to lazy right now so if anybody is motivated to do that, go ahead

EDIT SeineEloquenz: Removed featureSet loading notice as database is now saving dataset names
EDIT Weitstpringer: Reset GameOptions invitedEmail HashSet after each game creation #69

### CODE REVIEW

**Comment by SeineEloquenz** [comment]
Database now saves dataset name in patterns as well as of 77a2a92

**Comment by Weitspringer** [comment]
Solves #69

**Comment by bendixsonnenberg** [comment]
for the organiser termination we will need the organiser termination object in the backend.
I think we should now go ahead and merge this into master

**Comment by bendixsonnenberg** [comment]
Still need reviews to merge

**Pull request merged**
