### PR TITLE
Logger configuration

### LINKED ISSUE #147: [project][low prio] Describe logger configuration in README
Follow-up to issue #121 and pull-request #145: Describe (shortly) how the `tinylog` Logger can be configured (in particular, during productive use, with a config file - maybe already provide an example config file).

### PR DESCRIPTION
**Pull request by SeineEloquenz**
Added possibility for custom logger settings through a config file and necessary documentation

closes #147

### CODE REVIEW

**Comment by SeineEloquenz** [comment]
Adding a `Logger.properties` file to the docker-compose repo would not make sense as the file is only necessary if one wants to differ from the default way of logging. I also think an example properties is unnecessary as on the one hand there are far too many possible configurations for tinylog to create a useful example while and on the other the tinylog documentation is very in-depth so I think creating one from scratch should not pose a challenge

**Comment by bendixsonnenberg** [comment]
You are right.
The documentation still has to say in which exact location to put the config file

**Comment by SeineEloquenz** [comment]
The location is mentioned in the Logger Configuration section

**Comment by bendixsonnenberg** [comment]
sorry, apparently I'm incapable of reading

**Comment by bendixsonnenberg** [comment]
Sorry, apparently I'm incapable of reading

**Pull request merged**
