### PR TITLE
Restyle login page

### PR DESCRIPTION
**Pull request by SeineEloquenz**
I restyled the login page to make it look a bit nicer, opinions are welcome

### CODE REVIEW

**Comment by bendixsonnenberg** [comment]
this will create a conflict if #130 is merged

**Comment by SeineEloquenz** [comment]
I would propose to postpone this and merge if we have time after #130 is merged

**Comment by bendixsonnenberg** [comment]
> I would propose to postpone this and merge if we have time after #130 is merged

agreed

**Comment by bendixsonnenberg** [comment]
image
is this the way you want it to look?
because i think it's a bit off center

**Comment by SeineEloquenz** [comment]
It was centered on my end, that's... confusing

**Comment by SeineEloquenz** [comment]
It should, and does look, like this (on my end). Did you try hard-refreshing the page?
image

**Comment by bendixsonnenberg** [comment]
in chromium it does work, but firefox has problems with displaying it

**Comment by bendixsonnenberg** [comment]
correction it does work in firefox, i just hit shift instead of ctrl when doing a hard reload

**Comment by bendixsonnenberg** [comment]
the fields get too small if the browser window is reduced in size, but not small enough to be recognized as a mobile

**Comment by SeineEloquenz** [comment]
I rebased the branch to incorporate the missing configuration alert and fixed the width of the medium size class, content should now no longer get too small to be read

**Comment by bendixsonnenberg** [comment]
image
still seems to small to me.

**Comment by SeineEloquenz** [comment]
What was the size of the browser window?

**Pull request merged**
