### PR TITLE
Prevent gameCreator from using wrong ids

### PR DESCRIPTION
**Pull request by SeineEloquenz**
#38 
This commit fixed the bug on my machine

### CODE REVIEW

**Comment by SeineEloquenz** [comment]
Have you reset the database before trying with the new commit?

**Comment by SeineEloquenz** [comment]
Now working correctly on my machine

**Comment by bendixsonnenberg** [comment]
image

still not working on my end

**Comment by SeineEloquenz** [comment]
I can't reproduce the bug anymore, are you sure you have deleted all databases created beforehand and are on the latest version of the correct branch ? My second game is created correctly
image

**Comment by bendixsonnenberg** [comment]
still getting the same error

**Comment by bendixsonnenberg** [comment]
database in the begining
image
then redeploying to tomcat
registering new organiser
image
creating new game
image
database at that moment
image
terminating and deleting game
database: 
image
creating new game 
image
database: 
image

**Comment by bendixsonnenberg** [comment]
am i doing something wrong?

**Comment by SeineEloquenz** [comment]
Nothing that I'm aware of. I did exactly the same again and it worked perfectly fine

**Comment by bendixsonnenberg** [comment]
are you sure you have no changes that are not on origin/deleteGameFix

**Comment by SeineEloquenz** [comment]
Nothing to commit, nothing to push. My version history
image

**Comment by bendixsonnenberg** [comment]
now it works on my end.
had to perform `mvn clean`

**Pull request merged**
