### PR TITLE
Gamecreation modals

### PR DESCRIPTION
**Pull request by Weitspringer**
Prevent creating new games with same title / result database or overwrite patterns by accident.
Therefore, modals are shown asking the organiser if he intended that. If necessary, Organiser can terminate creation, but values in fields are not deleted.

### CODE REVIEW

**Comment by Weitspringer** [comment]
@SeineEloquenz Does this work on your machine?
Somehow, every time the function titleExists returns true...

**Comment by Weitspringer** [comment]
@SeineEloquenz Could you please screenshot with the Vue dev tool open?

**Comment by Weitspringer** [comment]
Has to do sth. with master merge

**Comment by SeineEloquenz** [comment]
Nothing changed
image

**Comment by Weitspringer** [comment]
Please show me the errors
 
 
  Am Di., Feb. 19, 2019 at 19:21 schrieb SeineEloquenz<notifications@github.com>:   
Nothing changed

**Comment by SeineEloquenz** [comment]
These?
image

**Comment by Weitspringer** [comment]
Yes thanks. I will look into that later. 
 
 
  Am Di., Feb. 19, 2019 at 19:30 schrieb SeineEloquenz<notifications@github.com>:   
These?

**Comment by Weitspringer** [comment]
@SeineEloquenz Creation page will be shown now, but every time titleExists returns true in the Backend. We should take a look at that...

**Comment by SeineEloquenz** [comment]
The method is working correctly.
image
image

When clicking on create in the gamecreation the method in the API is not being called, this is the issue here

**Comment by Weitspringer** [comment]
@SeineEloquenz I look into that now

**Comment by Weitspringer** [comment]
@SeineEloquenz seems like the response is not handled properly.
But does the titleExist method takes all games in count or only active games?

**Comment by SeineEloquenz** [comment]
All non deleted games

**Comment by Weitspringer** [comment]
@SeineEloquenz Does this work on your machine?

**Comment by Weitspringer** [comment]
Before we merge we can solve #166 the same way

**Comment by Weitspringer** [comment]
Solves #166

**Pull request merged**
